kind: Service
apiVersion: v1
metadata:
  name: metaphor
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: @ACM_CERTIFICATE_ARN@
    external-dns.alpha.kubernetes.io/hostname: metaphor-@K8S_NAMESPACE@.@DOMAIN@
  labels:
    run: metaphor
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
  selector:
    run: metaphor
  externalTrafficPolicy: Cluster
  type: LoadBalancer
